-- Promove para produção o fluxo validado de evidências e pesagens.
-- Não copia usuários, PEVs, rotas ou qualquer dado do ambiente de teste.

set local lock_timeout = '5s';
set local statement_timeout = '60s';

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role = any (array['admin','commercial','commercial_manager','driver','production'])) not valid;
alter table public.profiles validate constraint profiles_role_check;

create table if not exists public.route_evidences (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  stop_id bigint not null references public.route_stops(id) on delete cascade,
  pev_id bigint not null references public.pevs(id),
  evidence_type text not null,
  storage_path text not null,
  created_by uuid default auth.uid() references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  sharepoint_status text not null default 'pending',
  sharepoint_item_id text,
  sharepoint_url text,
  sharepoint_path text,
  sharepoint_sha256 text,
  sharepoint_synced_at timestamptz,
  sharepoint_started_at timestamptz,
  sharepoint_last_error text,
  sharepoint_attempts integer not null default 0,
  storage_deleted_at timestamptz,
  constraint route_evidences_evidence_type_check
    check (evidence_type = any (array['collection_material','delivery_drum_location','stop_location','drum','weighing_scale'])),
  constraint route_evidences_sharepoint_status_check
    check (sharepoint_status = any (array['pending','syncing','synced','error']))
);

create table if not exists public.route_weighings (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.routes(id) on delete cascade,
  stop_id bigint not null unique references public.route_stops(id) on delete cascade,
  pev_id bigint not null references public.pevs(id),
  weight_kg numeric not null check (weight_kg > 0),
  evidence_id bigint not null references public.route_evidences(id) on delete restrict,
  created_by uuid default auth.uid() references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.route_evidences enable row level security;
alter table public.route_weighings enable row level security;

revoke all on table public.route_evidences from anon;
revoke all on table public.route_weighings from anon;
grant select, insert on table public.route_evidences to authenticated;
grant select, insert on table public.route_weighings to authenticated;
grant all on table public.route_evidences to service_role;
grant all on table public.route_weighings to service_role;
grant usage, select on sequence public.route_evidences_id_seq to authenticated, service_role;
grant usage, select on sequence public.route_weighings_id_seq to authenticated, service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'rota-evidencias',
  'rota-evidencias',
  false,
  8388608,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create unique index if not exists route_evidences_required_stop_photo_uidx
on public.route_evidences (stop_id, evidence_type)
where evidence_type in ('stop_location','drum');

create index if not exists route_evidences_stop_idx
on public.route_evidences (stop_id, evidence_type);

create index if not exists route_evidences_sharepoint_queue_idx
on public.route_evidences (sharepoint_status, created_at);

create index if not exists route_evidences_sharepoint_cleanup_idx
on public.route_evidences (sharepoint_status, storage_deleted_at)
where sharepoint_status = 'synced' and storage_deleted_at is null;

create index if not exists route_stops_route_status_idx
on public.route_stops (route_id, status);

create index if not exists route_stops_production_queue_idx
on public.route_stops (route_id, sequence)
where status = 'completed' and service_type = 'collection';

create or replace function private.clear_pev_request_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.service_start := null;
  new.service_end := null;
  new.notes := '';
  new.internal_notes := '';
  return new;
end
$$;

drop trigger if exists pevs_clear_request_fields_on_insert on public.pevs;
create trigger pevs_clear_request_fields_on_insert
before insert on public.pevs
for each row execute function private.clear_pev_request_fields();

drop trigger if exists pevs_clear_request_fields_on_update on public.pevs;
create trigger pevs_clear_request_fields_on_update
before update on public.pevs
for each row execute function private.clear_pev_request_fields();

create or replace function private.production_can_access_route(p_route_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.current_app_role() = 'production', false)
    and exists (
      select 1
      from public.routes r
      where r.id = p_route_id
        and r.status = 'in_progress'
        and not exists (
          select 1
          from public.route_stops pending
          where pending.route_id = r.id
            and pending.status in ('pending','arrived')
        )
        and exists (
          select 1
          from public.route_stops collected
          where collected.route_id = r.id
            and collected.status = 'completed'
            and collected.service_type = 'collection'
            and not exists (
              select 1
              from public.route_weighings weighing
              where weighing.stop_id = collected.id
            )
        )
    )
$$;

create or replace function private.production_can_access_stop(p_stop_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.current_app_role() = 'production', false)
    and exists (
      select 1
      from public.route_stops stop
      where stop.id = p_stop_id
        and stop.status = 'completed'
        and stop.service_type = 'collection'
        and private.production_can_access_route(stop.route_id)
        and not exists (
          select 1
          from public.route_weighings weighing
          where weighing.stop_id = stop.id
        )
    )
$$;

create or replace function private.production_can_access_pev(p_pev_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.current_app_role() = 'production', false)
    and exists (
      select 1
      from public.route_stops stop
      where stop.pev_id = p_pev_id
        and private.production_can_access_stop(stop.id)
    )
$$;

create or replace function private.production_can_insert_evidence(
  p_route_id bigint,
  p_stop_id bigint,
  p_pev_id bigint,
  p_evidence_type text,
  p_created_by uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.current_app_role() = 'production', false)
    and p_created_by = auth.uid()
    and p_evidence_type = 'weighing_scale'
    and exists (
      select 1
      from public.route_stops stop
      where stop.id = p_stop_id
        and stop.route_id = p_route_id
        and stop.pev_id = p_pev_id
        and private.production_can_access_stop(stop.id)
    )
$$;

create or replace function private.production_can_insert_weighing(
  p_route_id bigint,
  p_stop_id bigint,
  p_pev_id bigint,
  p_evidence_id bigint,
  p_created_by uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.current_app_role() = 'production', false)
    and p_created_by = auth.uid()
    and exists (
      select 1
      from public.route_stops stop
      where stop.id = p_stop_id
        and stop.route_id = p_route_id
        and stop.pev_id = p_pev_id
        and private.production_can_access_stop(stop.id)
    )
    and exists (
      select 1
      from public.route_evidences evidence
      where evidence.id = p_evidence_id
        and evidence.route_id = p_route_id
        and evidence.stop_id = p_stop_id
        and evidence.pev_id = p_pev_id
        and evidence.evidence_type = 'weighing_scale'
        and evidence.created_by = auth.uid()
    )
$$;

revoke all on function private.production_can_access_route(bigint) from public, anon;
revoke all on function private.production_can_access_stop(bigint) from public, anon;
revoke all on function private.production_can_access_pev(bigint) from public, anon;
revoke all on function private.production_can_insert_evidence(bigint,bigint,bigint,text,uuid) from public, anon;
revoke all on function private.production_can_insert_weighing(bigint,bigint,bigint,bigint,uuid) from public, anon;
grant execute on function private.production_can_access_route(bigint) to authenticated;
grant execute on function private.production_can_access_stop(bigint) to authenticated;
grant execute on function private.production_can_access_pev(bigint) to authenticated;
grant execute on function private.production_can_insert_evidence(bigint,bigint,bigint,text,uuid) to authenticated;
grant execute on function private.production_can_insert_weighing(bigint,bigint,bigint,bigint,uuid) to authenticated;

drop policy if exists routes_read on public.routes;
create policy routes_read on public.routes
for select to authenticated
using (
  can_view_management()
  or (current_app_role() = 'driver' and driver_id = auth.uid())
  or (current_app_role() = 'commercial' and private.commercial_owns_route(id, auth.uid()))
  or private.production_can_access_route(id)
);

drop policy if exists stops_read on public.route_stops;
create policy stops_read on public.route_stops
for select to authenticated
using (
  exists (
    select 1
    from public.routes route
    where route.id = route_stops.route_id
      and (
        can_view_management()
        or (current_app_role() = 'driver' and route.driver_id = auth.uid())
      )
  )
  or (current_app_role() = 'commercial' and private.commercial_owns_pev(pev_id, auth.uid()))
  or private.production_can_access_stop(id)
);

drop policy if exists pevs_read on public.pevs;
create policy pevs_read on public.pevs
for select to authenticated
using (
  (
    deleted_at is null
    and (
      current_app_role() in ('admin','commercial_manager')
      or (current_app_role() = 'commercial' and commercial_owner_id = auth.uid())
      or private.driver_can_access_pev(id, auth.uid())
      or private.production_can_access_pev(id)
    )
  )
  or (
    deleted_at is not null
    and current_app_role() in ('admin','commercial_manager')
  )
);

drop policy if exists evidence_insert on public.route_evidences;
create policy evidence_insert on public.route_evidences
for insert to authenticated
with check (
  (
    current_app_role() = 'driver'
    and created_by = auth.uid()
    and evidence_type in ('stop_location','drum')
    and exists (
      select 1
      from public.route_stops stop
      join public.routes route on route.id = stop.route_id
      where stop.id = route_evidences.stop_id
        and stop.route_id = route_evidences.route_id
        and stop.pev_id = route_evidences.pev_id
        and stop.status in ('pending','arrived')
        and route.status = 'in_progress'
        and route.driver_id = auth.uid()
    )
  )
  or private.production_can_insert_evidence(route_id, stop_id, pev_id, evidence_type, created_by)
);

drop policy if exists evidence_read on public.route_evidences;
create policy evidence_read on public.route_evidences
for select to authenticated
using (
  can_view_management()
  or exists (
    select 1
    from public.routes route
    where route.id = route_evidences.route_id
      and route.driver_id = auth.uid()
  )
  or (
    current_app_role() = 'commercial'
    and private.commercial_owns_pev(pev_id, auth.uid())
  )
  or (
    current_app_role() = 'production'
    and created_by = auth.uid()
    and evidence_type = 'weighing_scale'
  )
);

drop policy if exists weighing_insert on public.route_weighings;
create policy weighing_insert on public.route_weighings
for insert to authenticated
with check (
  private.production_can_insert_weighing(route_id, stop_id, pev_id, evidence_id, created_by)
);

drop policy if exists weighing_read on public.route_weighings;
create policy weighing_read on public.route_weighings
for select to authenticated
using (
  can_view_management()
  or exists (
    select 1
    from public.routes route
    where route.id = route_weighings.route_id
      and route.driver_id = auth.uid()
  )
  or (
    current_app_role() = 'commercial'
    and private.commercial_owns_pev(pev_id, auth.uid())
  )
  or (
    current_app_role() = 'production'
    and created_by = auth.uid()
  )
);

drop policy if exists evidence_storage_insert on storage.objects;
create policy evidence_storage_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'rota-evidencias'
  and current_app_role() in ('driver','production')
  and owner_id = auth.uid()::text
);

drop policy if exists evidence_storage_read on storage.objects;
create policy evidence_storage_read on storage.objects
for select to authenticated
using (
  bucket_id = 'rota-evidencias'
  and (
    current_app_role() in ('admin','commercial_manager','commercial')
    or (
      current_app_role() in ('driver','production')
      and owner_id = auth.uid()::text
    )
  )
);

drop policy if exists evidence_storage_update on storage.objects;
create policy evidence_storage_update on storage.objects
for update to authenticated
using (
  bucket_id = 'rota-evidencias'
  and current_app_role() in ('driver','production')
  and owner_id = auth.uid()::text
)
with check (
  bucket_id = 'rota-evidencias'
  and current_app_role() in ('driver','production')
  and owner_id = auth.uid()::text
);

drop policy if exists evidence_storage_delete_own on storage.objects;
create policy evidence_storage_delete_own on storage.objects
for delete to authenticated
using (
  bucket_id = 'rota-evidencias'
  and current_app_role() in ('driver','production')
  and owner_id = auth.uid()::text
);

create or replace function private.require_driver_stop_photos()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  if new.status in ('completed','failed')
     and old.status is distinct from new.status
     and private.current_app_role() = 'driver' then
    select count(distinct evidence.evidence_type)
      into v_count
    from public.route_evidences evidence
    where evidence.stop_id = new.id
      and evidence.evidence_type in ('stop_location','drum');

    if v_count <> 2 then
      raise exception 'As fotos do local e do tambor são obrigatórias antes de encerrar a parada'
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end
$$;

drop trigger if exists route_stops_require_driver_photos on public.route_stops;
create trigger route_stops_require_driver_photos
before update of status on public.route_stops
for each row execute function private.require_driver_stop_photos();

create or replace function private.finish_route_after_weighing()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_finished boolean := false;
begin
  update public.route_stops
     set collected_weight_kg = new.weight_kg
   where id = new.stop_id
     and route_id = new.route_id
     and pev_id = new.pev_id;

  update public.routes route
     set status = 'finished',
         finished_at = coalesce(route.finished_at, now())
   where route.id = new.route_id
     and route.status = 'in_progress'
     and not exists (
       select 1
       from public.route_stops pending
       where pending.route_id = route.id
         and pending.status in ('pending','arrived')
     )
     and not exists (
       select 1
       from public.route_stops collected
       where collected.route_id = route.id
         and collected.status = 'completed'
         and collected.service_type = 'collection'
         and not exists (
           select 1
           from public.route_weighings weighing
           where weighing.stop_id = collected.id
         )
     )
  returning true into v_finished;

  if coalesce(v_finished, false) then
    insert into public.audit_logs(
      actor_id,
      action,
      entity_type,
      entity_id,
      summary,
      metadata
    )
    values (
      new.created_by,
      'finish',
      'route',
      new.route_id::text,
      'Rota finalizada automaticamente após conclusão das paradas e pesagens',
      jsonb_build_object('automatic', true, 'source', 'production_weighing')
    );
  end if;

  return new;
end
$$;

drop trigger if exists route_weighings_finish_route on public.route_weighings;
create trigger route_weighings_finish_route
after insert on public.route_weighings
for each row execute function private.finish_route_after_weighing();

alter table public.login_attempts enable row level security;

revoke all on function public.delete_user_force(uuid) from public, anon;
grant execute on function public.delete_user_force(uuid) to authenticated;
