-- Mantem a estrutura de producao compatível com o backend de rotas.
-- Esta migracao cria apenas a estrutura; nenhum dado do ambiente de teste e copiado.

create table if not exists public.driver_location_updates (
  id bigint generated by default as identity primary key,
  route_id bigint not null
    references public.routes(id) on delete cascade,
  driver_id uuid not null
    references public.profiles(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  accuracy_m double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists driver_location_route_time_idx
  on public.driver_location_updates (route_id, recorded_at desc);

alter table public.driver_location_updates enable row level security;

drop policy if exists location_insert on public.driver_location_updates;
create policy location_insert
  on public.driver_location_updates
  for insert
  to authenticated
  with check (
    (select public.current_app_role()) = 'driver'
    and driver_id = (select auth.uid())
    and exists (
      select 1
      from public.routes route
      where route.id = driver_location_updates.route_id
        and route.driver_id = (select auth.uid())
        and route.status = 'in_progress'
    )
  );

drop policy if exists location_read on public.driver_location_updates;
create policy location_read
  on public.driver_location_updates
  for select
  to authenticated
  using (
    (select public.can_view_management())
    or (
      (select public.current_app_role()) = 'driver'
      and driver_id = (select auth.uid())
    )
  );

revoke all on table public.driver_location_updates from anon;
revoke all on table public.driver_location_updates from authenticated;
grant select, insert on table public.driver_location_updates to authenticated;
grant all on table public.driver_location_updates to service_role;

revoke all on sequence public.driver_location_updates_id_seq from anon;
grant usage, select on sequence public.driver_location_updates_id_seq to authenticated;
grant all on sequence public.driver_location_updates_id_seq to service_role;

notify pgrst, 'reload schema';
